Repository SierraSystems/secure-file-storage, pull requests merged in 2020-06, with the labels that each got.

#16 fix typo
  README.md
Labels: documentation

#18 Test coverage and code climate for frontend
  .github/workflows/codeclimate-fe.yml
  .github/workflows/jest.yml
  src/frontend/package.json
Labels: do not merge, enhancement, frontend

#22 Simple S3 upload/delete controller
  credentials.csv
  src/middleware/secure-file-storage-api/pom.xml
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/controller/FileController.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/model/AmazonS3Config.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/AmazonS3ClientService.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/impl/AmazonS3ClientServiceImpl.java
  src/middleware/secure-file-storage-api/src/main/resources/application.properties
Labels: backend

#26 S3 Upload from frontend
  src/frontend/.env.example
  src/frontend/.gitignore
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/components/base/uploader/Uploader.js
  src/frontend/src/components/base/uploader/Uploader.test.js
  src/frontend/src/index.js
Labels: enhancement, frontend

#29 Add screenshots to readme
  README.md
Labels: documentation, enhancement, frontend

#33 Delete uploaded files
  src/frontend/src/components/base/uploader/Uploader.js
  src/frontend/src/components/base/uploader/Uploader.test.js
Labels: frontend

#34 BCSC Authentication
  .github/workflows/codeclimate-fe.yml
  README.md
  src/frontend/.env.example
  src/frontend/README.md
  src/frontend/package-lock.json
  src/frontend/package.json
  src/frontend/src/App.js
  src/frontend/src/__snapshots__/storyshots.test.js.snap
  src/frontend/src/components/base/bcscbutton/BcscButton.css
  src/frontend/src/components/base/bcscbutton/BcscButton.js
  src/frontend/src/components/base/bcscbutton/BcscButton.stories.js
  src/frontend/src/components/base/bcscbutton/BcscButton.test.js
  src/frontend/src/components/base/bcscbutton/__snapshots__/BcscButton.test.js.snap
  src/frontend/src/components/base/heading/Heading.js
  src/frontend/src/components/base/heading/__snapshots__/Heading.test.js.snap
  src/frontend/src/components/base/loader/Loader.css
  src/frontend/src/components/base/loader/Loader.js
  src/frontend/src/components/base/loader/Loader.stories.js
  src/frontend/src/components/base/loader/Loader.test.js
  src/frontend/src/components/base/loader/__snapshots__/Loader.test.js.snap
  src/frontend/src/components/base/uploader/Uploader.test.js
  src/frontend/src/components/base/userinfo/UserInfo.js
  src/frontend/src/components/base/userinfo/UserInfo.stories.js
  src/frontend/src/components/base/userinfo/UserInfo.test.js
  src/frontend/src/components/base/userinfo/__snapshots__/UserInfo.test.js.snap
  src/frontend/src/components/composite/login/Login.css
  src/frontend/src/components/composite/login/Login.js
  src/frontend/src/components/composite/login/Login.test.js
  src/frontend/src/components/page/home/Home.js
  src/frontend/src/components/page/home/Home.stories.js
  src/frontend/src/components/page/home/Home.test.js
  src/frontend/src/components/page/home/__snapshots__/Home.test.js.snap
  src/frontend/src/index.js
  src/frontend/src/modules/AuthenticationHelper.js
  src/frontend/src/modules/AuthenticationHelper.test.js
Labels: enhancement, frontend

#35 Add resource for s3 encryption
  README.md
Labels: documentation

#36 Add section about aws s3 default encryption
  README.md
Labels: documentation

#38 File Operations on S3
  src/middleware/secure-file-storage-api/pom.xml
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/controller/FileController.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/AmazonS3ClientService.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/SecureFileService.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/impl/SecureFileServiceImpl.java
Labels: backend

#39 Added in get filenames
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/controller/FileController.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/SecureFileService.java
  src/middleware/secure-file-storage-api/src/main/java/com/nttdata/securefilestorageapi/service/impl/SecureFileServiceImpl.java
  src/middleware/secure-file-storage-api/src/main/resources/application.yml
  tests/secure-file-storage.postman_collection.json
Labels: backend
